### ISSUE TITLE
How to find new messages? 

### ISSUE THREAD

**Issue by DavidAwad** [kurttheviking/python-simple-hipchat#15]
If there was a way to find the most recent comment that would be really convenient. I'm thinking something like  

While True:
if com = getComment() :
and have com be the most recent comment

**Comment by kurttheviking** [comment]
@DavidAwad seems like the "right way" to do this would be to check the [room's history](https://www.hipchat.com/docs/api/method/rooms/history); you can do this with the current v1 api so I am going to close this issue. if you'd like to submit a PR with an explicit method I would gladly review and merge.
